[package]
name = "avored-rust-cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.5", features = ["multipart"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tower-http = { version = "0.5.2", features = ["fs", "cors"] }
dotenvy = "0.15.7"
axum-extra = { version = "0.9.3", features = ["cookie", "cookie-signed"] }
futures = "0.3.30"
tower = "0.4.13"
argon2 = "0.5.2"
validator = { version = "0.17.0", features = ["derive"] }
rand = "0.8.5"
urlencoding = "2.1.3"
serde_json = "1.0.115"
surrealdb = { version = "1.3.1", features = ["kv-rocksdb"] }
jsonwebtoken = "9.3.0"
chrono = { version = "0.4.37", features = [] }