name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: 'react-admin'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'react-admin'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run releases
      run: npm run build
#    - name: Copy files via ssh
#      uses: appleboy/scp-action@master
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        key: ${{ secrets.SSH_KEY }}
#        source: "./dist"
#        target: ${{ secrets.REACT_TARGET_PATH }}
#
    - name: Copy files via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "./dist"
        target: ${{ secrets.REACT_TARGET_PATH }}

    - name: change file ownership
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: sudo chown -R www-data:www-data ${{ secrets.REACT_TARGET_PATH}}
